name: Linux Kernel 5.4.255

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  kernel:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Clone Linux Kernel 5.4.255
      - name: Clone Linux Kernel 5.4.255
        run: |
          set -e

          rm -rf /tmp/linux-5.4.255

          git clone \
            --depth 1 \
            --branch v5.4.255 \
            https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git \
            /tmp/linux-5.4.255

      # 3. Push Linux Kernel 5.4.255 ke main
      - name: Push Linux 5.4.255 to main
        run: |
          set -e

          echo "Copy Linux Kernel 5.4.255..."

          rsync -a \
            --delete \
            --exclude='.git' \
            /tmp/linux-5.4.255/ \
            ./

          echo "Check git repository..."
          git status

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "Tiada perubahan."
            exit 0
          fi

          git commit -m "Import Linux Kernel 5.4.255"

          git push origin HEAD:main
